# Generated by Django 5.0.2 on 2024-02-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Film",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100)),
                ("description", models.CharField(blank=True, max_length=150)),
                ("year", models.IntegerField(blank=True)),
                ("duration_min", models.IntegerField(blank=True)),
                ("country", models.CharField(blank=True, max_length=50)),
                ("genre", models.CharField(blank=True, max_length=100)),
                ("poster", models.CharField(blank=True, max_length=150)),
            ],
        ),
    ]
