# Generated by Django 5.0.2 on 2024-02-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="photo",
            field=models.ImageField(blank=True, upload_to="images/user"),
        ),
    ]
